### ISSUE TITLE
The software package fails to be installed according to the steps in the readme file.

### ISSUE THREAD

**Issue by majestichou** [avlmaps/AVLMaps#3]
I installed the software step by step according to the setup environment chapter.
```
git clone https://github.com/avlmaps/AVLMaps.git
conda create -n avlmaps python=3.8 -y  # or use virtualenv
conda activate avlmaps
conda install jupyter -y
cd AVLMaps
bash install.bash
```
I have successfully installed the packages in requirements.txt.
But when the command which is ` conda install habitat-sim=0.2.2 -c conda-forge -c aihabitat -y` is executed , something unexpected happens. The information is as follws:
```
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: \ unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
```
Conda is in the process of resolving the environment. I've been waiting half the day, and it's still working on the environment. I've never had this happen with conda. 
Is there a wrong version of some packages in the AVLMaps project, such as the python version?

**Comment by Tom-Huang** [comment]
Hi, thank you for your interest in our project. I tested the installation process just now and also noticed the conflict solving process. However, the process finished in very soon (less than one minute) on my computer with CPU `AMD Ryzen 9 PRO 7945 12-Core Processor`. The python version in the environment is 3.8.19. You can also try to create a new environment and install the habitat-sim shown in the install.bash file first and then pip install requirements.txt. This might avoid the conflict solving from the conda side.

**Comment by majestichou** [comment]
> Hi, thank you for your interest in our project. I tested the installation process just now and also noticed the conflict solving process. However, the process finished very soon (in less than one minute) on my computer with CPU `AMD Ryzen 9 PRO 7945 12-Core Processor`. The python version in the environment is 3.8.19 and it should not be an issue for habitat-sim=0.2.2. You can also try to create a new environment and install the habitat-sim shown in the install.bash file first and then pip install requirements.txt. This might avoid the conflict solving from the conda side.

Thank you for your answer. I would like to know how your anaconda channel is set up. What is the content of ~/.condarc?
My setup is as follows:
```
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch-lts: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  deepmodeling: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/
```
